### ISSUE TITLE
Issue loading mods - (server issue)

### ISSUE THREAD

**Issue by Ronkn** [bastimeyer/dayz-linux-workshop-setup#21]
Trying to join this server: 
45.35.100.35

And initially the terminal stated I was missing mods. So I clicked the links and subscribed/downloaded the missing mods. The game boots up and loads, then kicks me to the dayz main menu with this error see ![screenshot](https://user-images.githubusercontent.com/32688058/200138350-24ed9424-7a00-4315-a469-e691bd697d60.png)

I then went back to the steam page and unsubscribed and re-subbed to each mod. The issue regarding the missing "banovmap.pbo" file, I have it in that location. it did have a capitol "B" (Banov) but I tried making it lower case. All of this resulted in the same error. 

I also reverified the files. This launcher works fine for other servers. Below is my copy of your tool's code. The only changes I made are the STEAM_ROOT variable to match my steam location. 

[dayz-launcher.sh](https://github.com/bastimeyer/dayz-linux-cli-launcher/files/9944609/dayz-launcher.txt)

I confirmed on their discord that other players were indeed on the server so I doubt it's a server side issue. Not sure, any ideas?

**Comment by bastimeyer** [comment]
`STEAM_ROOT` is an environment variable, you are supposed to set it when launching the script if your steamapp directory path is different (like on Debian), not modify the script. See the readme or help text.

Without any debug log output, this is pretty useless. I can't guess what you were doing. Post the exact input and debug log output (the `-d` flag).

Also, according to the dayzsalauncher JSON API, `45.35.100.35` is an enoch server, aka Livonia. You either forgot to post the right query port (as there are multiple servers running on the same host), or you've posted the wrong IP address.
https://dayzsalauncher.com/api/v1/query/45.35.100.35/27016

Unless there is an issue with the launcher script which leads to loading the wrong mods, there's nothing I can do for you. The server's mod list is retrieved from a third party (dayzsalauncher JSON API), mods are located on your filesystem and symlinked as base64 encoded mod-ID folder names in the game directory, and then launch arguments are generated according to that and your other inputs, which are then passed to the steam client which launches the game client. So if the game client doesn't load one of those mods or if there's an issue with one of the mod contents, then it's not the fault of the launcher script and you'll have to figure this out on your own.

You should try running a game integrity validation which should also validate the subscribed and downloaded workshop mods. Other than that, if it's a problem with the mod itself (similar to issue #18), then you'll have to contact the mod author.

**Comment by bastimeyer** [comment]
All good.

Set the env var like this

```
STEAM_ROOT=/path/to/steamlibrary /path/to/dayz-launcher.sh arguments...
```
