### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by DUCKMAN2016** [bastimeyer/dayz-linux-workshop-setup#26]
i keep getting this, looks like line 324 is mods, do i need to set a mods route or just wipe them and try re-downloading them?
./dayz-launcher.sh: line 324: unexpected EOF while looking for matching

**Comment by bastimeyer** [comment]
I'm not going to spend any time on helping anyone here without any information at all in the issue post...

What exactly were you trying to do, which exact command did you run, and what was the exact output? Are you using the latest version?

On line 324 a log message gets written to the output, so what you've posted doesn't make much sense unless the script has been modified.
https://github.com/bastimeyer/dayz-linux-cli-launcher/blob/0.5.3/dayz-launcher.sh#L324

**Comment by DUCKMAN2016** [comment]
I resolved it.
