### ISSUE TITLE
Running the script and cant find path.

### ISSUE THREAD

**Issue by syneergyosu** [bastimeyer/dayz-linux-workshop-setup#27]
I was trying to run your script and for some reason it kept saying something about the path and i tried to fix it by manually choosing the path and it still kept giving me issues. I got dayz installed on my machine but not on /home but on another drive.

errors : DayZ not found or not installed at the Steam library given.

Any advice, can give more info if needed.

**Comment by bastimeyer** [comment]
The readme has all the details you need:

- https://github.com/bastimeyer/dayz-linux-cli-launcher#usage
- https://github.com/bastimeyer/dayz-linux-cli-launcher#examples

How do you expect someone to help you like this? You didn't provide any details at all, neither about your exact setup or the command you tried to run. The error message you posted is also not an error message that my launch script can output. You have to be way more precise when asking for help.

**Comment by syneergyosu** [comment]
My apologies I mixed up this repo with another. You can close this issue sorry for inconvenience.
